services:
  api:
    build: ./CentralizedLoggingApi
    container_name: centralized_logging_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:8080"   # Map host:container for HTTP
      - "5001:8081"   # Map host:container for HTTPS (if your app supports it)   
    depends_on:
      - db       
    volumes:
      - ./CentralizedLoggingApi/logs:/app/logs   

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: centralized_logging_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Bisp@123      
    ports:
      - "1433:1433"
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Bisp@123", "-Q", "SELECT 1"]
        interval: 10s
        retries: 10
        start_period: 30s            
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
