name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: usermanagementapi
            context: .
            dockerfile: UserManagementApi/Dockerfile
          - name: loggingapi
            context: .
            dockerfile: CentralizedLoggingApi/Dockerfile
          - name: integrationportal
            context: .
            dockerfile: ApiIntegrationMvc/Dockerfile
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/centralized-logging:latest
            ghcr.io/hasanjaved-developer/centralized-logging:latest
