name: .NET Tests (collector)

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Test (collector, Cobertura)
        run: |
          # Centralize results in one folder (still creates GUID subfolders inside)
          dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Upload coverage artifacts (Cobertura)
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-reports
          path: '**/TestResults/**/coverage.cobertura.xml'